# This rule is not used by the project dns-mesh-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dns.dnspolicies.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-mesh-controller
    app.kubernetes.io/managed-by: kustomize
  name: dnspolicy-viewer-role
rules:
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies/status
  verbs:
  - get
