# This rule is not used by the project dns-mesh-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dns.dnspolicies.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-mesh-controller
    app.kubernetes.io/managed-by: kustomize
  name: dnspolicy-editor-role
rules:
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies/status
  verbs:
  - get
