# This rule is not used by the project dns-mesh-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dns.dnspolicies.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-mesh-controller
    app.kubernetes.io/managed-by: kustomize
  name: dnspolicy-admin-role
rules:
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies
  verbs:
  - '*'
- apiGroups:
  - dns.dnspolicies.io
  resources:
  - dnspolicies/status
  verbs:
  - get
