apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dns-mesh-controller
    app.kubernetes.io/managed-by: kustomize
  name: dns-mesh-controller-manager-role-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-mesh-controller-manager-role
subjects:
- kind: ServiceAccount
  name: dns-mesh-controller-controller-manager
  namespace: {{.Release.Namespace}}
